---
title: "LING5503 語言的邏輯分析"
author: "謝舒凱 臺大語言學研究所"
subtitle: "LING5503 Logical Analysis of Language"
---

# 👏 歡迎


- Room: 綜 603 (部分內容剪輯上線)

- Office hours: By appointment

- Email: `shukaihsieh@ntu.edu.tw`

- Time: 14:20-17:10, Wed.

## 📜 課程網站

- [NTU COOL](https://cool.ntu.edu.tw/courses/26600)：指定教材、作業繳交

- [課程網站](lopentu.github.io/lal/)



## 📝 課程目的

- 瞭解語言分析的方式

- 認識世界語言的多樣性

- 學習不插電的計算語言思維


## 🏪 時程

| 時間           | 主題                                     | 課堂練習                   | TOL training            |
|:-------------:|:----------------------------------------:|:--------------------------:|:--------------|
| W1: 02/22  | 課程介紹             |          |  2/25-26 歷史語言、語言變異（林智凱教授）[1](https://us06web.zoom.us/rec/share/B7QwLX3oZrhgt5UycXI3LBlW6P2TlZEFcdNxvJg4xdJAbI1bsER71DEz8-pib2xr.xuTckkmXs0VahC4p) [2](https://us06web.zoom.us/rec/share/motucLx9m21QQpqp-qpVmYSVPIw87C5I5VFEpxbi6bIlvSFDfkYrIJNAXJg0qTYM.Duytvj9sAjX1DxBz)|
| W2: 03/01 | 語言類型與文化邏輯     |                 | 3/4-5 類型學與南島語言（江豪文博士）[1](https://us06web.zoom.us/rec/share/GeULivnzdImlRXy4zGNj0eKvlChggEZROt0gvh0ZjKFdH9P2kQFvmYix1WZVPDXR.2A9vBOw8wYwS8rbQ) [2](https://us06web.zoom.us/rec/share/waKM_IPgxpQkS6JG7z5mjLPOiRsXB6CzSrwfCdADZ5X4Ulohrdo67Tyh9rDvJBRX.D4v3QVTa-jwCIfeO)|
| W3: 03/08  | 語音的世界               |               |3/11-12 世界文字系統與阿爾泰語系（蕭素英教授）[1](https://drive.google.com/file/d/1u9gpAV5dDwGj7pq-vtGAOJRaHqN5qmam/view?usp=sharing) [2](https://drive.google.com/file/d/13eWdkxMCGPCI-XUWR72RPdfXw8ktange/view?usp=sharing) |
| W4: 03/15   | 語音的世界 |                             |3/18-19 語音變化（郭貞秀教授）[1](https://us06web.zoom.us/rec/share/915nIYUAz8azUzxk1JqZPDv5jgxvjnJyyPi0ImxCUldfpxI6rhsRIek2m7uy97kK.elRZUoMYQdYb-Gm0)[2](https://us06web.zoom.us/rec/share/3mbXDAVMVg130rTr_q52M4gaMtkbqczwvajLUovsRQC7J5qUF1pTDP4b35PTJHaY.oMBHNU_8wTk6ml6x) |
| W5: 03/22   | 構詞與句法 |                |3/25-26 構詞句法（許展嘉教授）|
| W6: 03/29   | 構詞與句法           |        | 4/1-2 語意與文化想像（謝舒凱教授）|
| W7: 04/05  | 清明節放假                |  ||
| W8: 04/12   | 期中考**       |            |                  |
| W9: 04/19   | 語言與數字表達                     | |                             |
| W10: 04/26   | 語意與文化     |          ||
| W11: 05/03   | 語意與文化    |         | |
| W12: 05/10  |語意與文化 |||
| W13: 05/17  |世界文字系統|||
| W14: 05/24 |人造語文系統||中小學生語言解謎鐵人賽（林口康橋，5/28）|
| W15: 05/31 |語言謎題設計||國際語奧命題委員會演講|
| W16: 06/07 |期末專題報告||二階國手培訓互動 (6:30-8:30)|


::: {.callout-tip}
## APLO (https://aplo.asia/) Asia Pacific Linguistics Olympiad (APLO) 
a regional linguistics olympiad with the aim of escalating attention to language and linguistics in the Asia Pacific region. The upcoming APLO will be held on April 9th, 2023.  
:::

::: {.callout-important}
爲了培訓臺灣選手參加亞太語奧決選，同時安排了週末日線上課程。課堂同學有興趣者可以登記加入旁聽。5 月份有機會與決選出之臺灣代表隊互動。
:::

---

## 🐇 要求 | Requirement

- 原則上第二週開始有一份課後練習作業 (見網站)，截止日爲隔週一晚上11:00， 上傳至 NTU COOL。

- `4/12` 有期中考。(從 **APLO 2023** 挑一題，可以團體形式進行答題。)

- 除閱讀指定閱讀之外，須完成一個期末報告或專案。

---

## 🏆 成績 | Grading

- 課堂參與 | Participation: 10%
- 平時作業 | Assignments: 30%
- 期中考 | Midterm: 20% 
- 期末專題與發表 | Final Project/Presentation: 40%

**遲交作業處理**

截止時間起，每天扣 5% 。有特殊事宜應該事先告知老師或助教。

## 😢 學術倫理 | Plagiarism

請大家自重自愛，不用別人要求。

## 🧠 期末報告 | Term project

- 可以個人或團體完成 (3 人以內)

    - 設計類似語奧題目，並附上清楚的語料來源與解題說明。
    
    - 設計與實作語言遊戲，不拘形式。

